{
 "title": "My Dashboard - BWCE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Job Completed",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_metrics_TOTAL_JOB_COUNT{AppName=\"order-mgmt.application\"}",
     "legendFormat": "BWCE"
    },
    {
     "expr": "app_metrics_flogo_flow_executions_total{app_name=\"order-app\", state=\"completed\", flow_name=\"MCI-SaveOrder\"}",
     "legendFormat": "Flogo"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "filters": [
      { "id": "eb5ac4ce", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "valueType": "string"
      }
     ],
     "limit": 100,
     "query": "{ resource.service.name = \"order-mgmt.application:1.0\" && span.ActivityName = \"Log\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Duration BWCE Rest",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "filters": [
      {
       "id": "673b3f1a",
       "operator": "=",
       "scope": "span",
       "tag": "ActivityName",
       "value": "Reply",
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "order-mgmt.application:1.0" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Duration Batch",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 4, "x": 5, "y": 11 },
   "targets": [
    {
     "filters": [
      {
       "id": "673b3f1a",
       "operator": "=",
       "scope": "span",
       "tag": "ActivityName",
       "value": [ "Timer" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "order-mgmt.application:1.0" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Application Flogo Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"apps-logs-via-otel-collector\"} |= `[flogo.` != `org_id=fake` != `pluginId=loki`"
    }
   ]
  },
  {
   "title": "Duration Flogo REST",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "targets": [
    {
     "filters": [
      {
       "id": "673b3f1a",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "order-app" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Application BWCE logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"apps-logs-via-otel-collector\"} |= `bwEngThread` != `dsUID=loki` != `org_id=fake`"
    }
   ]
  }
 ]
}